name: morie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  google_fonts: ^4.0.4
  font_awesome_flutter : ^10.6.0
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.1
  just_audio: ^0.9.36
  audio_video_progress_bar: ^2.0.1
  audioplayers: ^5.2.1
  assets_audio_player: ^3.1.1
  http: ^1.1.2
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
  - lib/assets/header.png
  - lib/assets/baby.png
  - lib/assets/meal.png
  - lib/assets/pregnant.png
  - lib/assets/nature_sounds.mp3