// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZITJj89SX5luHL7QO9yAtlRB_ocvFCX0',
    appId: '1:366532402875:web:6ccdb2faf33f57154c139e',
    messagingSenderId: '366532402875',
    projectId: 'morie-7f242',
    authDomain: 'morie-7f242.firebaseapp.com',
    storageBucket: 'morie-7f242.appspot.com',
    measurementId: 'G-EQ8D2DYQ4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD7Lh7vNLU1Z-SxPkIODL8AIRclO6Tsoc',
    appId: '1:366532402875:android:02c281b58211b4a74c139e',
    messagingSenderId: '366532402875',
    projectId: 'morie-7f242',
    storageBucket: 'morie-7f242.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf5QmjhXhUQ19KvFL8Ps9Y9AJWkZaXhoY',
    appId: '1:366532402875:ios:4f3e7f691d9d002c4c139e',
    messagingSenderId: '366532402875',
    projectId: 'morie-7f242',
    storageBucket: 'morie-7f242.appspot.com',
    iosBundleId: 'com.example.morie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf5QmjhXhUQ19KvFL8Ps9Y9AJWkZaXhoY',
    appId: '1:366532402875:ios:32eafae79a7bd1634c139e',
    messagingSenderId: '366532402875',
    projectId: 'morie-7f242',
    storageBucket: 'morie-7f242.appspot.com',
    iosBundleId: 'com.example.morie.RunnerTests',
  );
}
