// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5IYI2fRmyJqATLuabOQ2xPcE_cyViPQE',
    appId: '1:546992058889:web:556caee9bd7734127b3ed8',
    messagingSenderId: '546992058889',
    projectId: 'morie-c78f8',
    authDomain: 'morie-c78f8.firebaseapp.com',
    storageBucket: 'morie-c78f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmxVcdCbTcRiHdMOPBx7Flflx4PiiUZvc',
    appId: '1:546992058889:android:7b601039edf716227b3ed8',
    messagingSenderId: '546992058889',
    projectId: 'morie-c78f8',
    storageBucket: 'morie-c78f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVLuWv__dY_JjQ47yx9KBEUvDX6fRlKBM',
    appId: '1:546992058889:ios:c17b1e36589635bd7b3ed8',
    messagingSenderId: '546992058889',
    projectId: 'morie-c78f8',
    storageBucket: 'morie-c78f8.appspot.com',
    iosBundleId: 'com.example.morie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVLuWv__dY_JjQ47yx9KBEUvDX6fRlKBM',
    appId: '1:546992058889:ios:cb3f7d08861431af7b3ed8',
    messagingSenderId: '546992058889',
    projectId: 'morie-c78f8',
    storageBucket: 'morie-c78f8.appspot.com',
    iosBundleId: 'com.example.morie.RunnerTests',
  );
}
